services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somePassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: somePassword
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
